# -*- coding: utf-8 -*-
"""Diwali_sales_analysis_(EDA).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fcAZxJWtVS5FDHmsVX0QZwGrY2ea4etU
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np # to work on array
import pandas as pd # work on data frame
import matplotlib.pyplot as plt #visualizing data
# %matplotlib inline
import seaborn as sns

df = pd.read_csv('/content/Diwali Sales Data.csv', encoding='ISO-8859-1')

df.shape

df.head(10)

df.info()

#drop blank column
df.drop(['Status','unnamed1'],axis=1,inplace =True)

df.head()

df.info()

pd.isnull(df)

pd.isnull(df).sum()

df.shape

df.dropna(inplace=True) # inplace true makes the changes in df

df.shape

#change data type

df['Amount']=df['Amount'].astype('int')

df['Amount'].dtypes

df.columns

#rename columns

df.rename(columns= {'Marital_Status':'Marriage'}) #dict - not saves as we havent used inplace = True

df.describe()

# use describe for specific columns

df[['Age', 'Orders', 'Amount']].describe()

"""## Exploratory Data Analysis

GENDER
"""

ax =sns.countplot(x='Gender',data=df)

print(ax)

ax =sns.countplot(x='Gender',data=df)
for bars in ax.containers:
  ax.bar_label(bars)

# Analysis : Female count more than male count

df.groupby(['Gender'],as_index =False)['Amount'].sum().sort_values(by='Amount',ascending=False)

# Analysis : Female count as well as amount is more

sales_gen = df.groupby(['Gender'],as_index=False)['Amount'].sum().sort_values(by = 'Amount',ascending=False)

sales_gen.head()

sns.barplot(x='Gender',y='Amount',data=sales_gen)

# Conclusion : From the above graphs we can see that most fo the buyers are women and purchasing power of women s greator

"""AGE"""

sns.countplot(data=df,x='Age Group',hue='Gender')

ax = sns.countplot(data=df,x='Age Group',hue ='Gender')
for bars in ax.containers:
  ax.bar_label(bars)

